### ISSUE TITLE
Question: Migration to koin or Gson

### ISSUE THREAD

**Issue by mwshubham** [VMadalin/kotlin-sample-app#13]
Is there any ongoing thinking to refractor/migrate the project to [Koin](https://github.com/InsertKoinIO/koin)/ [Moshi](https://github.com/square/moshi). As Moshi seems to be GSON 3.0 and possibly Koin will replace dagger in the near future.

**Comment by necatisozer** [comment]
> Koin will replace dagger in the near future.
Nope. Android team declared Dagger as recommended DI framework and will improve it to work simpler with Kotlin & Android.
https://developer.android.com/training/dependency-injection/dagger-basics

**Comment by mwshubham** [comment]
True. They have recommended DI. No need to think about koin as of now.
