### ISSUE TITLE
Question about using plugin in the id of plugins 

### ISSUE THREAD

**Issue by Stegnerd** [VMadalin/kotlin-sample-app#14]
## Description
 In regards to this project it is a great learning tool and I was curious to walk through it! My question is in the BuildPlugins file you set all the plugins to use plugins.xxxx. for example BuildPlugins.detekt, yet when I try to build it says that it cannot find a plugin with an id plugin.detekt. But if I use the following: io.gitlab.arturbosch.detekt it is found and moves to the next error in the build.  Can you elaborate on that?

Thank you so much

**Comment by Stegnerd** [comment]
I have done much learning over the past day and I understand now. I found this tidbit of documentation  that explained it for me: https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/ .

> if you use the imperative apply() function to apply a plugin,  then you will have to use the configure<T>() function to configure that plugin

 You brought in the plugin as an implementation to use its imports when creating the custom plugins. Again thanks for the great learning resource!

**Comment by VMadalin** [comment]
First of all thanks @Stegnerd for summit your question and my apologise to and answer you before. 
You are right is the way to apply a plugin to a specific gradle.kts file similar to the groovy https://proandroiddev.com/configure-gradle-in-different-files-ecbf69bd5b56 

I recommend you this repo: https://github.com/gradle/kotlin-dsl-samples/tree/master/samples that have a list of a lot of examples related gradle-dsl
